"""Configure the world enemy-part impact MI/Style after authored assets exist.

Prerequisites:
1. DreamShader generated /Game/DreamMaterials/World/M_WacomBattleEnemyPartImpactPixel.
2. Run the WacomBuildBattleEnemyPartImpactNiagara commandlet. It validates the User
   parameter/renderer contract and idempotently builds all three emitter stacks.

The Niagara graph is intentionally generated by WacomEditor C++, not Python. Python only
connects the generated System, MI and Style without relying on unstable reflected Niagara internals.
"""

import unreal


MATERIAL_DIR = "/Game/DreamMaterials/World"
BASE_MATERIAL_PATH = MATERIAL_DIR + "/M_WacomBattleEnemyPartImpactPixel"
MATERIAL_INSTANCE_PATH = MATERIAL_DIR + "/MI_WacomBattleEnemyPartImpactPixel_Default"
NIAGARA_SYSTEM_PATH = "/Game/Wacom/VFX/Battle/NS_WacomBattleEnemyPartImpact_Pixel"
STYLE_DIR = "/Game/Wacom/UI/Battle/WorldImpact"
STYLE_PATH = STYLE_DIR + "/DA_BattleEnemyPartImpactStyle_Pixel"
DEBUG_SNAKE_HOST_PATH = "/Game/Wacom/Core/Enemy/BP_SnakeHost_Debug"

def load_required(asset_path, label):
    asset = unreal.load_asset(asset_path)
    if not asset:
        raise RuntimeError(f"{label} is missing: {asset_path}")
    return asset


def enable_niagara_sprite_usage(material):
    try:
        material.set_editor_property("used_with_niagara_sprites", True)
    except Exception as error:
        raise RuntimeError(
            "Unable to enable Used With Niagara Sprites on the generated material"
        ) from error
    compile_errors = unreal.MaterialEditingLibrary.recompile_material(material)
    if compile_errors:
        formatted_errors = "\n".join(str(error) for error in compile_errors)
        raise RuntimeError(
            "Enemy impact material failed to compile after enabling Niagara Sprite usage:\n"
            + formatted_errors
        )
    unreal.EditorAssetLibrary.save_loaded_asset(material)


def load_or_create_material_instance(parent):
    material_instance = unreal.load_asset(MATERIAL_INSTANCE_PATH)
    if not material_instance:
        material_instance = unreal.AssetToolsHelpers.get_asset_tools().create_asset(
            "MI_WacomBattleEnemyPartImpactPixel_Default",
            MATERIAL_DIR,
            unreal.MaterialInstanceConstant,
            unreal.MaterialInstanceConstantFactoryNew(),
        )
    if not material_instance:
        raise RuntimeError("Failed to create enemy-part impact material instance")

    unreal.MaterialEditingLibrary.set_material_instance_parent(material_instance, parent)
    scalar_values = {
        "ImpactPrimaryWeight": 0.50,
        "ImpactSecondaryWeight": 0.32,
        "ImpactPixelColumns": 12.0,
        "ImpactOutlineWidth": 0.055,
        "ImpactCoreBrightness": 1.35,
        "ImpactDecorativeGlow": 0.85,
    }
    vector_values = {
        "ImpactPrimaryColor": unreal.LinearColor(0.58, 0.80, 1.0, 1.0),
        "ImpactSecondaryColor": unreal.LinearColor(0.96, 0.82, 0.42, 1.0),
        "ImpactAccentColor": unreal.LinearColor(0.88, 0.30, 0.72, 1.0),
    }
    for name, value in scalar_values.items():
        unreal.MaterialEditingLibrary.set_material_instance_scalar_parameter_value(
            material_instance, name, value)
    for name, value in vector_values.items():
        unreal.MaterialEditingLibrary.set_material_instance_vector_parameter_value(
            material_instance, name, value)
    unreal.EditorAssetLibrary.save_loaded_asset(material_instance)
    return material_instance


def load_or_create_style(system, material_instance):
    style_asset = unreal.load_asset(STYLE_PATH)
    if not style_asset:
        factory = unreal.DataAssetFactory()
        factory.set_editor_property(
            "data_asset_class", unreal.WacomBattleEnemyPartImpactStyle)
        style_asset = unreal.AssetToolsHelpers.get_asset_tools().create_asset(
            "DA_BattleEnemyPartImpactStyle_Pixel",
            STYLE_DIR,
            unreal.WacomBattleEnemyPartImpactStyle,
            factory,
        )
    if not style_asset:
        raise RuntimeError("Failed to create enemy-part impact Style")

    values = {
        "impact_material_instance": material_instance,
        "target_confirmed_intensity": 0.70,
        "damage_intensity_base": 0.75,
        "damage_intensity_sqrt_scale": 0.10,
        "damage_intensity_min": 0.80,
        "damage_intensity_max": 1.80,
        "target_confirmed_coverage_multiplier": 1.20,
        "damage_coverage_multiplier": 1.20,
        "fallback_impact_diameter_centimeters": 96.0,
        "minimum_impact_diameter_centimeters": 72.0,
        "maximum_impact_diameter_centimeters": 260.0,
        "camera_depth_offset_centimeters": 2.0,
        "target_confirmed_sound_volume_multiplier": 1.0,
        "target_confirmed_sound_pitch_multiplier": 1.0,
        "target_confirmed_sound_pitch_variation": 0.03,
        "damage_sound_volume_multiplier": 1.0,
        "damage_sound_pitch_multiplier": 1.0,
        "damage_sound_pitch_variation": 0.03,
    }
    if system:
        values["impact_system"] = system
    for name, value in values.items():
        style_asset.set_editor_property(name, value)
    unreal.EditorAssetLibrary.save_loaded_asset(style_asset)
    return style_asset


def assign_debug_snake_default(style):
    host_blueprint = load_required(DEBUG_SNAKE_HOST_PATH, "Debug Snake Host")
    host_cdo = unreal.get_default_object(host_blueprint.generated_class())
    host_cdo.set_editor_property("default_impact_style", style)
    unreal.EditorAssetLibrary.save_loaded_asset(host_blueprint)


base_material = load_required(BASE_MATERIAL_PATH, "Enemy impact DreamShader material")
enable_niagara_sprite_usage(base_material)
default_instance = load_or_create_material_instance(base_material)
load_or_create_style(None, default_instance)
niagara_system = load_required(NIAGARA_SYSTEM_PATH, "Enemy impact Niagara System")
default_style = load_or_create_style(niagara_system, default_instance)
assign_debug_snake_default(default_style)
unreal.log("Wacom enemy-part pixel impact material, Style and Debug Snake binding configured")
